### ISSUE TITLE
Newsletter link

### ISSUE THREAD

**Issue by mickdekkers** [ferrous-systems/sealed-rust#1]
Hi! I found this repo though Changelog Nightly, it was in the list of top starred new repositories across GitHub yesterday :clap:

I just wanted to give you a quick heads-up: it appears that the link to join your newsletter at the bottom of the pitch document is missing. That is to say, it's currently set to `#`, so clicking it does nothing.

I applaud your efforts and I'm excited to see where this project goes.

Mick

**Comment by jamesmunns** [comment]
Thanks for reporting this! We've updated the link to sign up for our newsletter. You can sign up for our newsletter [here](http://eepurl.com/guoC6P) if you are interested!
